apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton
  namespace: argocd
spec:
  destination:
    namespace: tekton
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: tekton-pipeline
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://cdfoundation.github.io/tekton-helm-chart/
    targetRevision: 1.9.1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true