apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tkn-git-clone
  namespace: tekton
spec:
  destination:
    namespace: tekton
    server: https://kubernetes.default.svc
  project: default
  source:
    path: git-clone.yaml
    repoURL: https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.6/
    targetRevision: HEAD